services:
  db:
    image: postgres:15
    env_file: ".env"
    container_name: astrosky_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    container_name: astrosky_backend
    ports:
      - "8090:8090"
    depends_on:
      - db

volumes:
  pgdata: